# Generated by Django 5.0.2 on 2024-02-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('route_name', models.CharField(max_length=100)),
                ('route_origin', models.CharField(max_length=100)),
                ('route_destination', models.CharField(max_length=100)),
                ('stops', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('vehicle_id', models.CharField(max_length=100)),
                ('route_id', models.CharField(max_length=10)),
                ('driver_name', models.CharField(max_length=100)),
                ('trip_distance', models.FloatField()),
            ],
        ),
    ]
